### PR TITLE
Link Code of Conduct

### PR DESCRIPTION
**Pull request by terrajobst**
See [this policy rule](https://github.com/dotnet/org-policy/blob/master/doc/PR15.md) for more details.

### CODE REVIEW

**Comment by terrajobst** [comment]
@StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
wow, you're bringing back memories ! 10 years ago !

I'd merge this if I had write access. let me ask around...

**Comment by StephaneDelcroix** [comment]
@terrajobst if you have write access, go ahead and merge, or consider archiving the project

**Comment by akoeplinger** [comment]
It would be better to archive this repo, the last commit was 9years ago.

**Comment by terrajobst** [comment]
> It would be better to archive this repo, the last commit was 9years ago.

Done.

**Pull request merged**
